[package]
name = "promisqs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw_sync = "0.1.5"
shared_memory = "0.12.4"
thiserror = "1.0.38"
zerocopy = "0.6.1"
